// Generated by jextract

package io.ygdrasil.wgpu.internal.jvm.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WGPUInstanceFeatures {
 *     const WGPUChainedStruct *nextInChain;
 *     WGPUBool timedWaitAnyEnable;
 *     size_t timedWaitAnyMaxCount;
 * }
 * }
 */
public class WGPUInstanceFeatures {

    WGPUInstanceFeatures() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        wgpu_h.C_POINTER.withName("nextInChain"),
        wgpu_h.C_INT.withName("timedWaitAnyEnable"),
        MemoryLayout.paddingLayout(4),
        wgpu_h.C_LONG.withName("timedWaitAnyMaxCount")
    ).withName("WGPUInstanceFeatures");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout nextInChain$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInChain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const WGPUChainedStruct *nextInChain
     * }
     */
    public static final AddressLayout nextInChain$layout() {
        return nextInChain$LAYOUT;
    }

    private static final long nextInChain$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const WGPUChainedStruct *nextInChain
     * }
     */
    public static final long nextInChain$offset() {
        return nextInChain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const WGPUChainedStruct *nextInChain
     * }
     */
    public static MemorySegment nextInChain(MemorySegment struct) {
        return struct.get(nextInChain$LAYOUT, nextInChain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const WGPUChainedStruct *nextInChain
     * }
     */
    public static void nextInChain(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInChain$LAYOUT, nextInChain$OFFSET, fieldValue);
    }

    private static final OfInt timedWaitAnyEnable$LAYOUT = (OfInt)$LAYOUT.select(groupElement("timedWaitAnyEnable"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPUBool timedWaitAnyEnable
     * }
     */
    public static final OfInt timedWaitAnyEnable$layout() {
        return timedWaitAnyEnable$LAYOUT;
    }

    private static final long timedWaitAnyEnable$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPUBool timedWaitAnyEnable
     * }
     */
    public static final long timedWaitAnyEnable$offset() {
        return timedWaitAnyEnable$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPUBool timedWaitAnyEnable
     * }
     */
    public static int timedWaitAnyEnable(MemorySegment struct) {
        return struct.get(timedWaitAnyEnable$LAYOUT, timedWaitAnyEnable$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPUBool timedWaitAnyEnable
     * }
     */
    public static void timedWaitAnyEnable(MemorySegment struct, int fieldValue) {
        struct.set(timedWaitAnyEnable$LAYOUT, timedWaitAnyEnable$OFFSET, fieldValue);
    }

    private static final OfLong timedWaitAnyMaxCount$LAYOUT = (OfLong)$LAYOUT.select(groupElement("timedWaitAnyMaxCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t timedWaitAnyMaxCount
     * }
     */
    public static final OfLong timedWaitAnyMaxCount$layout() {
        return timedWaitAnyMaxCount$LAYOUT;
    }

    private static final long timedWaitAnyMaxCount$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t timedWaitAnyMaxCount
     * }
     */
    public static final long timedWaitAnyMaxCount$offset() {
        return timedWaitAnyMaxCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t timedWaitAnyMaxCount
     * }
     */
    public static long timedWaitAnyMaxCount(MemorySegment struct) {
        return struct.get(timedWaitAnyMaxCount$LAYOUT, timedWaitAnyMaxCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t timedWaitAnyMaxCount
     * }
     */
    public static void timedWaitAnyMaxCount(MemorySegment struct, long fieldValue) {
        struct.set(timedWaitAnyMaxCount$LAYOUT, timedWaitAnyMaxCount$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

