// Generated by jextract

package io.ygdrasil.wgpu.internal.jvm.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef WGPUWaitStatus (*WGPUProcInstanceWaitAny)(WGPUInstance, size_t, WGPUFutureWaitInfo *, uint64_t)
 * }
 */
public class WGPUProcInstanceWaitAny {

    WGPUProcInstanceWaitAny() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment instance, long futureCount, MemorySegment futures, long timeoutNS);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        wgpu_h.C_INT,
        wgpu_h.C_POINTER,
        wgpu_h.C_LONG,
        wgpu_h.C_POINTER,
        wgpu_h.C_LONG_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = wgpu_h.upcallHandle(WGPUProcInstanceWaitAny.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(WGPUProcInstanceWaitAny.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment instance, long futureCount, MemorySegment futures, long timeoutNS) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, instance, futureCount, futures, timeoutNS);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

